const data = {
    products:[
        {
            _id:'1',
            name: 'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/d1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name: 'Adidas Slim Shirt',
            category:'Shirts',
            image:'/images/d2.jpg',
            price: 100,
            brand: 'Adidas',
            rating: 4,
            numReviews:10,
            description:'high quality product',
        },

        {
            _id:'3',
            name: 'Lacoste Shirt',
            category:'Shirts',
            image:'/images/d3.jpg',
            price: 129,
            brand: 'Lacoste',
            rating: 4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name: 'Nike Pants',
            category:'Pants',
            image:'/images/p1.jpg',
            price: 320,
            brand: 'Nike',
            rating: 4.9,
            numReviews:15,
            description:'high quality product',
        },
        {
            _id:'5',
            name: 'Puma',
            category:'Pants',
            image:'/images/p2.jpg',
            price: 620,
            brand: 'Puma',
            rating: 3.5,
            numReviews:50,
            description:'high quality product',
        },
        {
            _id:'6',
            name: 'Adidas Pants',
            category:'Pants',
            image:'/images/p3.jpg',
            price: 920,
            brand: 'Nike',
            rating: 5,
            numReviews:9,
            description:'high quality product',
        },
    ]
}
export default data;